## Credentials for PreLink Web Service.
---
# wsdl_url: 'http://41.77.12.32/clinicservice.asmx?WSDL'
wsdl_url: 'https://lims.mlw.medcol.mw/clinicservice.asmx?WSDL'
wsdl_namspace: 'http://www.prelink.co.za/'
station_id: '42c99ae0-965f-e011-afb0-00215af546ac'
pass_code: '3fb19b7c-ae36-4383-974a-5ab199d9ffdc'
